export interface Companies {
    id: string,
    ruc: string,
    razon_social: string,
    nombre_comercial: string,
    usuario_sol: string,
    password_sol: string,
    password_p12: string,
    estado: string,
    sol_web: string,
    password_web: string,
    vencimiento_certificado: string,
    otros: string | null,
    id_emisor: string,
    ubigeo: string,
    departamento: string,
    provincia: string,
    distrito: string,
    direccion: string,
    local: string,
    apikey: string,
    modo: string,
    ubicacion: string,
    url_connect: string | null,
    url_ose: string | null
}